Added new recording params and filter
plivo/plivo-ruby pull request #215
Opened 2023-04-05 10:47 UTC by anindya-plivo

2023-04-10 06:32 UTC, prashantp-plivo requested changes

2023-04-10 06:32 UTC, prashantp-plivo commented on lib/plivo/version.rb
> +  VERSION = "4.39.1".freeze
As it is not a patch, increase the minor version instead of the patch version. New version should be 4.40.0

2023-04-12 07:40 UTC, prashantp-plivo requested changes

2023-04-12 07:40 UTC, prashantp-plivo commented on README.md
> +gem 'plivo', '>= 4.39.1'
Change this one also to 4.40.0

2023-04-12 11:07 UTC, prashantp-plivo approved these changes

2023-05-14 11:21 UTC, abhishekGupta-Plivo commented on lib/plivo/resources/recordings.rb
> +          recording_storage_duration__gt recording_storage_duration__gte
missing filter [recording_storage_duration] to search on 24 Hour window

2023-05-31 08:13 UTC, PuneetAgrawal-plivo approved these changes

2023-05-31 08:48 UTC, merged